language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
addons:
    postgresql: "9.6"
services:
    - postgresql
sudo: false
install:
    - pip install tox
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then tox -e coverage,coverage-report,coveralls,flake8,doc8,pep257,mypy; fi
matrix:
    fast_finish: true
notifications:
    email: false
